name: Fake Secret Leak Test

on:
  push:
    branches: [main]

jobs:
  expose-fake-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print fake secret to logs
        run: |
          echo "This is a fake GitHub token: github_pat_nyDcGRF5keuE3zD-Ryy=qut2CmsnQcEef270UetXA!n0gEsp1OrLVeUDxU6ohwqmYl8p/2B6ep-tY6-3I4-ZaO5M!3KGjQnjZcTp!lHU?1/KFghJB2rFYjiSAtD37KcOQHddF/t=Kxgj430HErT04OBG39lz5KYbs/ijJ5C3HN9Puj3Pp!qkd1Q339ILeia=-ilsuRNDIhxiQ159PEEvZ?8XnZQPWyGfilpclsOjL-cAjIvf5YTQN"

      - name: Save fake secret to artifact
        run: |
          echo "github_pat_nyDcGRF5keuE3zD-Ryy=qut2CmsnQcEe430HErT04OBG39lz5KYbs/ijJ5C3HN9Puj3Pp!qkd1Q339ILeia=-ilsuRNDIhxiQ159PEEvZ?8XnZQPWyGfilpclsOjL-cAjIvf5YTQN" > fake_secret.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fake-secret-artifact
          path: fake_secret.txt
