name: Fake Secret Leak Test

on:
  push:
    branches: [main]

jobs:
  expose-fake-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print fake secret to logs
        run: |
          echo "This is a fake GitHub token: ghp_FAKE1234567890fakeTokenExample"

      - name: Save fake secret to artifact
        run: |
          echo "ghp_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0" > fake_secret.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fake-secret-artifact
          path: fake_secret.txt
